BEGIN;

ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.day_mileage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_counter ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.query_record ENABLE ROW LEVEL SECURITY;

COMMIT;
